name: qrscan
description: A Plug-in for dart, which help you scanning barcode and qrcode with android device.
version: 0.3.3
homepage: https://github.com/leyan95/qrcode_scanner

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.2

flutter:
  plugin:
    platforms:
      android:
        package: com.shinow.qrscan
        pluginClass: QrscanPlugin
